### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by Ken4scholars** [arcanemachine/django-menu-maker#1]
Hi and thank you for this repo. I just noticed that the demo site is no longer working. Can you take a look at it, please? Thanks

**Comment by arcanemachine** [comment]
Sorry about that, I've been moving all my hobby projects to new server and everything's a mess right now.

I've set up a URL that points to the demo site on the old server: https://ken4scholars-dmm.nicholasmoen.com

The above URL will work until I get the new server up and running, in which case I will shut down server that the above URL points to.

**Comment by Ken4scholars** [comment]
Thanks, I really appreciate it!

> Sorry about that, I've been moving all my hobby projects to new server and everything's a mess right now.
> 
> I've set up a URL that points to the demo site on the old server: https://ken4scholars-dmm.nicholasmoen.com
> 
> The above URL will work until I get the new server up and running, in which case I will shut down server that the above URL points to.

**Comment by arcanemachine** [comment]
The new server is up, so I shut down the old one. the https://ken4scholars-dmm.nicholasmoen.com/ will no longer work, but the old one should be reliable now: https://django-menu-maker.nicholasmoen.com/
